apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx-app
    version: v1
spec:
  containers:
    - name: web
      image: novinrepo:8082/docker/nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP